---
title: "[TIL] DAY8 계산기 Lv1 트러블 슈팅"
categories: [내일배움캠프, TIL]
tag: [개인 과제, 본캠프, 트러블슈팅, 예외처리, 자바, 입력처리]
date: 2025-02-26 21:00:00 +0900
toc_sticky: true
---
### TODO
***
✔️ 자바 기초 문법 다지기 2주차 정리

✔️ 자바 기초 문법 다지기 3주차 완강

✔️ 계산기 개인 과제 Lv1 완료

✔️ TIL 작성

### 오늘 배운 것
***
#### 변수 scope 문제
예외 처리를 위해 try-catch문을 사용했는데, 해당 scope 밖을 벗어나면 변수를 사용할 수 없는 문제가 발생했다.

```java
int num1 = 0;
int num2 = 0;
Scanner sc = new Scanner(System.in);
String input = "";
while (!input.equals("exit")) {
  try {
  System.out.print("첫 번째 숫자를 입력하세요: ");
  num1 = sc.nextInt();
  if (num1 < 0) {
    System.out.println("양의 정수만 입력이 가능합니다.");
    return;
  }
  System.out.print("두 번째 숫자를 입력하세요: ");
  num2 = sc.nextInt();
  if (num2 < 0) {
    System.out.println("양의 정수만 입력이 가능합니다.");
    return;
  }
} catch (InputMismatchException e) {
  System.out.println("다른 문자를 입력했습니다.");
  return;
}
```

그래서 변수를 try-catch문 밖으로 뺴내었고 변수를 초기화하여 사용했다.

#### 연산 기능 예외 처리
연산 기능 구현 중, 0으로 나누는 경우 `ArithmeticException`이 발생하여 프로그램이 강제 종료되는 문제가 있었다. 

자바에서는 0으로 나누는 연산에서 예외가 발생하며, 별도의 예외 처리를 하지 않으면 프로그램이 종료된다. 

```java
try {
  switch (operator) {
    case '+':
      result = num1 + num2;
      break;
    case '-':
      result = num1 - num2;
      break;
    case '*':
      result = num1 * num2;
      break;
    case '/':
      result = num1 / num2;
      break;
    default:
      System.out.println("잘못된 사칙연산 기호입니다.");
      return;
  }
} catch (ArithmeticException e) {
  System.out.println("0으로 나눌 수 없습니다.");
  return;
}
```

이를 해결하기 위해 try-catch문을 사용하여 해결했다. 입력 받은 두 번째 숫자가 0이고 연산자가 /인 경우 프로그램이 종료되도록 했다. 다른 방법이 더 있는지는 Lv2를 진행하면서 알아봐야겠다.

### 느낀점
***
항상 이런 문제를 해결할 때마다 느끼는 건 기능을 구현하는 것 보다 예외를 발견하고 처리하는 것이 더 힘들다는 점이다. 정해진 요구사항 외의 부분은 결국 개발자의 몫이니까 말이다. 지금 예외가 발생하면 프로그램이 종료되도록 처리해둔 부분이 매우 신경쓰인다. 내일 Lv2를 진행하면서 저 부분도 수정할 방법을 찾아봐야겠다.

### 내일 학습할 것
- 계산기 Lv2 시작하기
- 계산기 Lv1 연산 부분 예외처리 생각해보기
- 자바 3주차 강의 정리하기
- 백준 1문제 풀기
